# **Women Cloth Reviews Prediction with Multinomial Naive Bayes**

**The multinomial Naive Bayes classifier is suitabe for classification with discrete features(e.g.,word counts for test classification).The multinomial distribution normally requires integer feature counts. However , in practice, fractional counts such as tf-idf may also work.**

# **Import Library**

In [3]:
import numpy as np

In [1]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

# **Import Dataset**

In [6]:
df=pd.read_csv("https://github.com/YBIFoundation/MachineLearning/raw/main/Dataset/Women%20Clothing%20E-Commerce%20Review.csv")

In [7]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [10]:
df.shape

(23486, 10)

# **Missing Values**

In [11]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [12]:
df[df['Review']==""]=np.NaN

In [13]:
df['Review'].fillna("No Review",inplace=True)

In [14]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [15]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# **Define Target(y) and feature(X)**

In [17]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [19]:
X=df['Review']

In [20]:
y=df['Review']


In [21]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# **Train_Test_Split**

In [22]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, stratify=y, random_state=2529)

In [54]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion to Tokens**

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
cv=CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [57]:
X_train=cv.fit_transform(X_train)

In [58]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'yellow color', 'yes runs',
       'yoga pants'], dtype=object)

In [59]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [60]:
X_test=cv.fit_transform(X_test)

In [61]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years come', 'yoga pants',
       'zipper little'], dtype=object)

In [62]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Get Model Train**

In [63]:
from sklearn.naive_bayes import MultinomialNB

In [64]:
model= MultinomialNB()

In [65]:
model.fit(X_train, y_train)

MultinomialNB()

# **Get Model Prediction**

In [66]:
y_pred=model.predict(X_test)

In [67]:
y_pred.shape

(7046,)

In [68]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

# **Get Probability of Each Predicted Class**

In [69]:
model.predict_proba(X_test)

array([[5.43140171e-02, 9.45685983e-01],
       [1.58169512e-01, 8.41830488e-01],
       [7.31367350e-03, 9.92686326e-01],
       ...,
       [3.92486843e-04, 9.99607513e-01],
       [2.24756691e-01, 7.75243309e-01],
       [5.78360255e-02, 9.42163975e-01]])

# **Get Model Evaluation**

In [70]:
from sklearn.metrics import confusion_matrix, classification_report

In [71]:
print(confusion_matrix(y_test, y_pred))

[[ 449 1134]
 [ 989 4474]]


In [72]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.31      0.28      0.30      1583
           1       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046



# **Recategories Rating as Poor(0) and Good (1)**

In [102]:
df['Rating'].value_counts()

Rating
0    23486
Name: count, dtype: int64

**Re-Rating as 1,2,3 as 0 and 4,5 as 1**

In [104]:
df.replace({'Rating' : {1 : 0 ,2 : 0 ,3 : 0 ,4 : 1 ,5 : 1 }}, inplace=True)

In [105]:
y=df['Rating']

In [106]:
X=df['Review']

# **Train_Test_Split**

In [107]:
from sklearn.model_selection import train_test_split

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, stratify=y, random_state=2529)

In [109]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Features Text Conversion to Tokens**

In [110]:
from sklearn.feature_extraction.text import CountVectorizer

In [111]:
cv=CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [112]:
X_train=cv.fit_transform(X_train)

In [113]:
X_test=cv.fit_transform(X_test)

# **Get Re-Train**

In [114]:
from sklearn.naive_bayes import MultinomialNB

In [115]:
model= MultinomialNB()

In [116]:
model.fit(X_train, y_train)

MultinomialNB()

# **Get Model Prediction**

In [117]:
y_pred=model.predict(X_test)

In [118]:
y_pred.shape

(7046,)

In [119]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

# **Get Model Evalution**

In [120]:
from sklearn.metrics import confusion_matrix, classification_report

In [121]:
print(confusion_matrix(y_test, y_pred))

[[7046]]


In [122]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7046

    accuracy                           1.00      7046
   macro avg       1.00      1.00      1.00      7046
weighted avg       1.00      1.00      1.00      7046

